# Generated by Django 4.2.7 on 2023-11-21 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishPond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_change_date', models.DateField(default=django.utils.timezone.now)),
                ('water_change_time', models.TimeField()),
                ('water_level', models.CharField(choices=[('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=10)),
                ('water_quality', models.CharField(choices=[('clear', 'Clear'), ('fairly_clear', 'Fairly Clear'), ('cloudy', 'Cloudy')], max_length=20)),
                ('algae_presence', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('high', 'High')], max_length=10)),
                ('feed_type', models.CharField(choices=[('2mm', '2mm'), ('3mm', '3mm'), ('4mm', '4mm'), ('6mm', '6mm'), ('9mm', '9mm')], max_length=10)),
                ('feed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feed_time', models.TimeField()),
                ('number_of_fish_stocked', models.IntegerField()),
                ('fish_size_or_weight', models.CharField(max_length=50)),
                ('signs_of_illness', models.TextField(blank=True)),
                ('medications_administered', models.TextField(blank=True)),
                ('number_of_fish_harvested', models.IntegerField()),
                ('harvested_fish_size_or_weight', models.CharField(max_length=50)),
                ('general_observations', models.TextField(blank=True)),
                ('unexpected_events', models.TextField(blank=True)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repairs_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
